using SpecGenerator.Config;
using SpecGenerator.Modeling;

namespace SpecGenerator.Emitting;

/// <summary>
/// Emits a leaf command C# class for a single OpenAPI operation.
/// </summary>
public static class OperationCommandEmitter
{
    public static string Emit(
        OperationModel op,
        string serviceClassName,
        string ns,
        DataplaneOptionPackConfig? dataplanePackConfig = null
    )
    {
        var isDataPlane = dataplanePackConfig is not null;
        var w = new CodeWriter();

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591");
        w.Line("using System.Text.Json.Nodes;");
        w.Line("using Console.Cli.Http;");
        w.Line("using Console.Cli.Shared;");
        w.Line("using Console.Rendering;");
        if (isDataPlane)
            w.Line("using Azure.ResourceManager;");
        w.Line();
        w.Line($"namespace {ns};");
        w.Line();

        var summary = op.Description is { Length: > 0 }
            ? op.Description.Replace("\n", " ").Replace("\r", "")
            : $"{NamingEngine.KebabToPascal(op.CliName)} operation.";

        w.Line($"/// <summary>{EscapeXml(summary)}</summary>");
        if (op.DetailedDescription is { Length: > 0 })
            w.Line(
                $"/// <remarks>{EscapeXml(op.DetailedDescription.Replace("\n", " ").Replace("\r", ""))}</remarks>"
            );

        // Determine scope flags (computed here so both field decls and ExecuteAsync can use them)
        var isMergedList = op.MergedSubscriptionUrlTemplate is not null;
        var usesStorageAccount =
            !isDataPlane
            && op.UrlTemplate.Contains("{accountName}", StringComparison.OrdinalIgnoreCase);

        // When StorageAccountOptionPack absorbs sub/rg, don't emit separate packs
        var usesResourceGroup =
            !isDataPlane
            && !usesStorageAccount
            && op.UrlTemplate.Contains("{resourceGroupName}", StringComparison.OrdinalIgnoreCase);
        var usesSubscription =
            !isDataPlane
            && !usesStorageAccount
            && op.UrlTemplate.Contains("{subscriptionId}", StringComparison.OrdinalIgnoreCase);

        // Derive property and variable names for the dataplane pack
        var urlPropName = isDataPlane ? FlagToPropName(dataplanePackConfig!.UrlCliFlag) : null;
        var baseUrlVar = isDataPlane ? FieldToBaseUrlVar(dataplanePackConfig!.FieldName) : null;

        w.Block(
            $"public partial class {op.ClassName}(AuthOptionPack auth) : CommandDef",
            () =>
            {
                w.Line($"public override string Name => \"{op.CliName}\";");
                if (isDataPlane)
                    w.Line("protected override bool IsDataPlane => true;");
                if (op.HttpMethod is "DELETE" or "PUT" or "POST")
                    w.Line("protected override bool IsDestructive => true;");
                w.Line();

                if (isDataPlane)
                {
                    // Data-plane: explicit URL flag overrides ARM-resolved endpoint
                    w.Line($"[CliOption(\"{dataplanePackConfig!.UrlCliFlag}\")]");
                    w.Line($"public partial string? {urlPropName} {{ get; }}");
                    w.Line();
                    w.Line($"public readonly {dataplanePackConfig.ClassName} {dataplanePackConfig.FieldName} = new();");
                    w.Line();
                }
                else
                {
                    if (usesStorageAccount)
                        w.Line("public readonly StorageAccountOptionPack StorageAccount = new();");
                    // Merged list always needs ResourceGroupOptionPack (--resource-group is optional)
                    else if (usesResourceGroup || isMergedList)
                        w.Line("public readonly ResourceGroupOptionPack ResourceGroup = new();");
                    else if (usesSubscription)
                        w.Line("public readonly SubscriptionOptionPack Subscription = new();");
                }

                w.Line("public readonly RenderOptionPack Render = new();");
                w.Line();

                // CLI params (path params other than subscription/rg, plus query params)
                foreach (var param in op.CliParams)
                {
                    if (
                        usesStorageAccount
                        && param.ParamIn == "path"
                        && param.UrlParameterName.Equals(
                            "accountName",
                            StringComparison.OrdinalIgnoreCase
                        )
                    )
                        continue; // absorbed by StorageAccountOptionPack

                    var requiredAttr = param.Required ? ", Required = true" : "";
                    if (!string.IsNullOrWhiteSpace(param.Description))
                        w.Line(
                            $"/// <summary>{EscapeXml(param.Description.Replace("\n", " ").Replace("\r", ""))}</summary>"
                        );
                    w.Line($"[CliOption(\"{param.CliFlag}\"{requiredAttr})]");
                    w.Line($"public partial string? {param.PropertyName} {{ get; }}");
                    w.Line();
                }

                // Body properties
                if (op.Body is { FlattenedProperties.Count: > 0 })
                {
                    foreach (var bp in op.Body.FlattenedProperties)
                    {
                        var typeName =
                            bp.TypeHint == "bool" ? "bool"
                            : bp.TypeHint == "int" ? "int"
                            : bp.TypeHint == "double" ? "double"
                            : "string";
                        var nullable = $"{typeName}?";
                        var requiredAttr = bp.Required ? ", Required = true" : "";

                        if (!string.IsNullOrWhiteSpace(bp.Description))
                            w.Line(
                                $"/// <summary>{EscapeXml(bp.Description.Replace("\n", " ").Replace("\r", ""))}</summary>"
                            );
                        w.Line($"[CliOption(\"{bp.CliFlag}\"{requiredAttr})]");
                        w.Line($"public partial {nullable} {bp.PropertyName} {{ get; }}");
                        w.Line();
                    }
                }

                // --body-json escape hatch (always present if operation has a body)
                if (op.Body is not null)
                {
                    w.Line(
                        "/// <summary>Supply the full request body as a JSON string (overrides individual options).</summary>"
                    );
                    w.Line("[CliOption(\"--body-json\")]");
                    w.Line("public partial string? BodyJson { get; }");
                    w.Line();
                }

                // --no-wait for LRO
                if (op.IsLro)
                {
                    w.Line(
                        "/// <summary>Do not wait for the long-running operation to complete.</summary>"
                    );
                    w.Line("[CliOption(\"--no-wait\")]");
                    w.Line("public partial bool NoWait { get; }");
                    w.Line();
                }

                w.Line("private readonly AuthOptionPack _auth = auth;");
                w.Line();

                // ExecuteAsync
                w.Block(
                    "protected override async Task<int> ExecuteAsync(CancellationToken ct)",
                    () =>
                    {
                        if (isDataPlane)
                            w.Line(
                                $"var client = new AzureRestClient(_auth.GetCredential(), \"{dataplanePackConfig!.Scope}\");"
                            );
                        else
                            w.Line("var client = new AzureRestClient(_auth.GetCredential());");

                        if (isDataPlane)
                            w.Line(
                                $"var {baseUrlVar} = {urlPropName} ?? (await {dataplanePackConfig!.FieldName}.ResolveDataplaneRefAsync(new ArmClient(_auth.GetCredential()), ct)).ToString().TrimEnd('/');"
                            );

                        // Build path
                        if (isDataPlane)
                            EmitDataPlanePathBuilder(w, op, baseUrlVar!);
                        else
                            EmitPathBuilder(
                                w,
                                op,
                                isMergedList,
                                usesResourceGroup,
                                usesSubscription,
                                usesStorageAccount
                            );
                        w.Line();

                        if (op.IsPaged)
                        {
                            EmitPagedExecution(w, op);
                        }
                        else if (op.IsLro)
                        {
                            EmitLroExecution(w, op);
                        }
                        else if (op.Body is not null)
                        {
                            EmitBodyExecution(w, op);
                        }
                        else
                        {
                            EmitSimpleExecution(w, op);
                        }

                        w.Line("return 0;");
                    }
                );
            }
        );

        return w.ToString();
    }

    private static void EmitDataPlanePathBuilder(CodeWriter w, OperationModel op, string baseUrlVar)
    {
        var expr = op.UrlTemplate;

        // Replace path params with property access
        foreach (var param in op.CliParams.Where(p => p.ParamIn == "path"))
        {
            expr = expr.Replace(
                $"{{{param.UrlParameterName}}}",
                $"{{{param.PropertyName}}}",
                StringComparison.OrdinalIgnoreCase
            );
        }

        // Emit: var path = $"{baseUrlVar}/keys/{KeyName}/...";
        w.Line($"var path = $\"{{{baseUrlVar}}}{expr}\";");
    }

    /// <summary>Converts a CLI flag like "--vault-url" to a C# property name "VaultUrl".</summary>
    private static string FlagToPropName(string cliFlag)
    {
        var stripped = cliFlag.TrimStart('-');
        return string.Concat(
            stripped.Split('-').Select(s => s.Length > 0 ? char.ToUpper(s[0]) + s[1..] : "")
        );
    }

    /// <summary>Converts a field name like "KeyVault" to a local variable name "keyVaultBaseUrl".</summary>
    private static string FieldToBaseUrlVar(string fieldName) =>
        char.ToLower(fieldName[0]) + fieldName[1..] + "BaseUrl";

    private static void EmitPathBuilder(
        CodeWriter w,
        OperationModel op,
        bool isMergedList,
        bool usesResourceGroup,
        bool usesSubscription,
        bool usesStorageAccount = false
    )
    {
        if (isMergedList)
        {
            // Conditional path: RG-scope when --resource-group (or env var) is given,
            // subscription-scope otherwise. Both branches use ResourceGroupOptionPack.
            var rgPath = BuildPathExpression(
                op.UrlTemplate,
                op,
                usesResourceGroup: true,
                usesSubscription: true
            );
            var subPath = BuildMergedSubscriptionPath(op.MergedSubscriptionUrlTemplate!, op);
            w.Line(
                "var effectiveRg = ResourceGroup.ResourceGroupName ?? Environment.GetEnvironmentVariable(\"AZURE_RESOURCE_GROUP\");"
            );
            w.Line($"var path = effectiveRg is not null");
            w.Line($"    ? {rgPath}");
            w.Line($"    : {subPath};");
        }
        else
        {
            var pathExpr = BuildPathExpression(
                op.UrlTemplate,
                op,
                usesResourceGroup,
                usesSubscription,
                usesStorageAccount
            );
            w.Line($"var path = {pathExpr};");
        }
    }

    private static string BuildPathExpression(
        string urlTemplate,
        OperationModel op,
        bool usesResourceGroup,
        bool usesSubscription,
        bool usesStorageAccount = false
    )
    {
        var expr = urlTemplate;

        if (usesStorageAccount)
        {
            expr = expr.Replace(
                    "{subscriptionId}",
                    "{StorageAccount.Subscription.RequireSubscriptionId()}",
                    StringComparison.OrdinalIgnoreCase
                )
                .Replace(
                    "{resourceGroupName}",
                    "{StorageAccount.ResourceGroup.RequireResourceGroupName()}",
                    StringComparison.OrdinalIgnoreCase
                )
                .Replace(
                    "{accountName}",
                    "{StorageAccount.RequireAccountName()}",
                    StringComparison.OrdinalIgnoreCase
                );
        }
        else
        {
            // Replace known absorbed params with option-pack calls
            expr = expr.Replace(
                    "{subscriptionId}",
                    usesResourceGroup ? "{ResourceGroup.Subscription.RequireSubscriptionId()}"
                        : usesSubscription ? "{Subscription.RequireSubscriptionId()}"
                        : "{subscriptionId}"
                )
                .Replace("{resourceGroupName}", "{ResourceGroup.RequireResourceGroupName()}");
        }

        // Replace remaining path parameters with property access
        foreach (var param in op.CliParams.Where(p => p.ParamIn == "path"))
        {
            expr = expr.Replace(
                $"{{{param.UrlParameterName}}}",
                $"{{{param.PropertyName}}}",
                StringComparison.OrdinalIgnoreCase
            );
        }

        return $"$\"{expr}\"";
    }

    /// <summary>
    /// Builds the subscription-scope path for a merged list command.
    /// Always uses ResourceGroup.Subscription for subscriptionId.
    /// </summary>
    private static string BuildMergedSubscriptionPath(string urlTemplate, OperationModel op)
    {
        var expr = urlTemplate.Replace(
            "{subscriptionId}",
            "{ResourceGroup.Subscription.RequireSubscriptionId()}",
            StringComparison.OrdinalIgnoreCase
        );

        foreach (var param in op.CliParams.Where(p => p.ParamIn == "path"))
        {
            expr = expr.Replace(
                $"{{{param.UrlParameterName}}}",
                $"{{{param.PropertyName}}}",
                StringComparison.OrdinalIgnoreCase
            );
        }

        return $"$\"{expr}\"";
    }

    private static void EmitPagedExecution(CodeWriter w, OperationModel op)
    {
        var itemsProp = op.ItemsPropertyName ?? "value";
        var nextLinkProp = op.NextLinkPropertyName ?? "nextLink";

        w.Line(
            $"var allItems = client.GetAllAsync(path, \"{op.ApiVersion}\", \"{itemsProp}\", \"{nextLinkProp}\", ct);"
        );
        w.Line(
            "var renderer = Render.GetRendererFactory().CreateCollectionRenderer<System.Text.Json.Nodes.JsonNode>();"
        );
        w.Line("await renderer.RenderAllAsync(System.Console.Out, allItems, ct);");
    }

    private static void EmitLroExecution(CodeWriter w, OperationModel op)
    {
        if (op.Body is not null)
        {
            EmitBodyBuild(w, op);
            w.Line(
                $"var httpResp = await client.SendRawAsync(HttpMethod.{TitleCase(op.HttpMethod)}, path, \"{op.ApiVersion}\", body, ct);"
            );
        }
        else
        {
            w.Line(
                $"var httpResp = await client.SendRawAsync(HttpMethod.{TitleCase(op.HttpMethod)}, path, \"{op.ApiVersion}\", null, ct);"
            );
        }

        w.Block(
            "if (!NoWait)",
            () =>
            {
                w.Line(
                    $"var result = await LroPoller.PollAsync(httpResp, client, \"{op.ApiVersion}\", ct);"
                );
                w.Line(
                    "await Render.GetRendererFactory().CreateRendererForType(typeof(System.Text.Json.Nodes.JsonNode))"
                );
                w.Line("    .RenderAsync(System.Console.Out, result, ct);");
            }
        );
    }

    private static void EmitBodyExecution(CodeWriter w, OperationModel op)
    {
        EmitBodyBuild(w, op);
        w.Line(
            $"var result = await client.SendAsync(HttpMethod.{TitleCase(op.HttpMethod)}, path, \"{op.ApiVersion}\", body, ct);"
        );
        w.Line(
            "await Render.GetRendererFactory().CreateRendererForType(typeof(System.Text.Json.Nodes.JsonNode))"
        );
        w.Line("    .RenderAsync(System.Console.Out, result, ct);");
    }

    private static void EmitSimpleExecution(CodeWriter w, OperationModel op)
    {
        w.Line(
            $"var result = await client.SendAsync(HttpMethod.{TitleCase(op.HttpMethod)}, path, \"{op.ApiVersion}\", null, ct);"
        );
        w.Line(
            "await Render.GetRendererFactory().CreateRendererForType(typeof(System.Text.Json.Nodes.JsonNode))"
        );
        w.Line("    .RenderAsync(System.Console.Out, result, ct);");
    }

    private static void EmitBodyBuild(CodeWriter w, OperationModel op)
    {
        w.Line("var body = BodyJson is { } rawJson");
        w.Line("    ? JsonNode.Parse(rawJson)!.AsObject()");
        w.Line("    : new JsonObject");
        w.Line("    {");
        w.Indent();
        w.Indent();

        if (op.Body is { FlattenedProperties.Count: > 0 })
        {
            // Group nested properties by their parent JSON key
            var topLevelEntries = new Dictionary<string, List<BodyPropertyModel>>(
                StringComparer.OrdinalIgnoreCase
            );

            foreach (var bp in op.Body.FlattenedProperties)
            {
                if (bp.ParentJsonKey is not null)
                {
                    // Nested sub-property (e.g., sku.name)
                    if (!topLevelEntries.TryGetValue(bp.ParentJsonKey, out var subList))
                    {
                        subList = [];
                        topLevelEntries[bp.ParentJsonKey] = subList;
                    }

                    subList.Add(bp);
                }
                else
                {
                    // Top-level scalar
                    topLevelEntries[bp.JsonPropertyName] = [bp];
                }
            }

            foreach (var (key, props) in topLevelEntries)
            {
                if (props.Count == 1 && props[0].ParentJsonKey is null)
                {
                    // Simple scalar top-level property
                    var bp = props[0];
                    w.Line($"[\"{bp.JsonPropertyName}\"] = JsonValue.Create({bp.PropertyName}),");
                }
                else
                {
                    // Nested object (e.g., sku: { name: SkuName })
                    w.Line($"[\"{key}\"] = new JsonObject");
                    w.Line("{");
                    w.Indent();
                    foreach (var bp in props)
                        w.Line(
                            $"[\"{bp.JsonPropertyName}\"] = JsonValue.Create({bp.PropertyName}),"
                        );
                    w.Outdent();
                    w.Line("},");
                }
            }
        }

        w.Outdent();
        w.Line("};");
        w.Outdent();
    }

    private static string TitleCase(string method) =>
        method switch
        {
            "GET" => "Get",
            "PUT" => "Put",
            "POST" => "Post",
            "DELETE" => "Delete",
            "PATCH" => "Patch",
            _ => method,
        };

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
