using SpecGenerator.Config;
using SpecGenerator.Modeling;

namespace SpecGenerator.Emitting;

/// <summary>
/// Emits a leaf command C# class for a single OpenAPI operation.
/// </summary>
public static class OperationCommandEmitter
{
    public static string Emit(
        OperationModel op,
        string serviceClassName,
        string ns,
        DataplaneOptionPackConfig? dataplanePackConfig = null,
        ResourceOptionPackConfig? resourcePackConfig = null
    )
    {
        var isDataPlane = dataplanePackConfig is not null;
        var w = new CodeWriter();

        // Does this specific operation target a named resource via resourcePackConfig?
        var usesResourcePack =
            resourcePackConfig is not null
            && !isDataPlane
            && op.UrlTemplate.Contains(
                $"{{{resourcePackConfig.AbsorbedParam}}}",
                StringComparison.OrdinalIgnoreCase
            );

        // Derive the local ARM-id variable name (e.g. KeyVault -> keyVaultId)
        var armIdVar = usesResourcePack
            ? char.ToLower(resourcePackConfig!.FieldName[0])
                + resourcePackConfig.FieldName[1..]
                + "Id"
            : null;

        // Determine scope flags (computed before file header so all emitters can use them)
        var isMergedList = op.MergedSubscriptionUrlTemplate is not null;
        var usesStorageAccount =
            !isDataPlane
            && !usesResourcePack
            && op.UrlTemplate.Contains("{accountName}", StringComparison.OrdinalIgnoreCase);

        // When StorageAccountOptionPack or ResourceOptionPack absorbs sub/rg, don't emit separate packs
        var usesResourceGroup =
            !isDataPlane
            && !usesStorageAccount
            && !usesResourcePack
            && op.UrlTemplate.Contains("{resourceGroupName}", StringComparison.OrdinalIgnoreCase);
        var usesSubscription =
            !isDataPlane
            && !usesStorageAccount
            && !usesResourcePack
            && op.UrlTemplate.Contains("{subscriptionId}", StringComparison.OrdinalIgnoreCase);

        // Primary path param: first resource-specific path param by position in URL template.
        // Used to apply hierarchical name parsing (ResourceNameResolver) to generic ARM commands.
        var primaryPathParam =
            usesResourceGroup && !isMergedList
                ? op
                    .CliParams.Where(p => p.ParamIn == "path")
                    .OrderBy(p =>
                        op.UrlTemplate.IndexOf(
                            $"{{{p.UrlParameterName}}}",
                            StringComparison.OrdinalIgnoreCase
                        )
                    )
                    .FirstOrDefault()
                : null;

        var resourceType = primaryPathParam is not null
            ? ExtractResourceType(op.UrlTemplate)
            : null;
        var usesResourceNameResolver = primaryPathParam is not null && resourceType is not null;

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591");
        w.Line("using System.Text.Json.Nodes;");
        w.Line("using Console.Cli.Http;");
        w.Line("using Console.Cli.Shared;");
        w.Line("using Console.Rendering;");
        if (
            isDataPlane
            || usesResourcePack
            || usesResourceNameResolver
            || usesSubscription
            || usesResourceGroup
            || isMergedList
            || usesStorageAccount
        )
            w.Line("using Azure.ResourceManager;");
        w.Line();
        w.Line($"namespace {ns};");
        w.Line();

        var summary = op.Description is { Length: > 0 }
            ? op.Description.Replace("\n", " ").Replace("\r", "")
            : $"{NamingEngine.KebabToPascal(op.CliName)} operation.";

        w.Line($"/// <summary>{EscapeXml(summary)}</summary>");
        if (op.DetailedDescription is { Length: > 0 })
            w.Line(
                $"/// <remarks>{EscapeXml(op.DetailedDescription.Replace("\n", " ").Replace("\r", ""))}</remarks>"
            );

        w.Block(
            $"public partial class {op.ClassName}(AuthOptionPack auth) : CommandDef",
            () =>
            {
                w.Line($"public override string Name => \"{op.CliName}\";");
                if (isDataPlane)
                    w.Line("protected internal override bool IsDataPlane => true;");
                if (op.HttpMethod is "DELETE" or "PUT" or "POST")
                    w.Line("protected internal override bool IsDestructive => true;");
                w.Line();

                if (isDataPlane)
                {
                    w.Line(
                        $"public readonly {dataplanePackConfig!.ClassName} {dataplanePackConfig.FieldName} = new();"
                    );
                    w.Line();
                }
                else if (usesResourcePack)
                {
                    // RM resource-pack: single option pack identifies the named resource
                    w.Line(
                        $"public readonly {resourcePackConfig!.ClassName} {resourcePackConfig.FieldName} = new();"
                    );
                    w.Line();
                }
                else
                {
                    if (usesStorageAccount)
                        w.Line("public readonly StorageAccountOptionPack StorageAccount = new();");
                    // Merged list always needs ResourceGroupOptionPack (--resource-group is optional)
                    else if (usesResourceGroup || isMergedList)
                        w.Line("public readonly ResourceGroupOptionPack ResourceGroup = new();");
                    else if (usesSubscription)
                        w.Line("public readonly SubscriptionOptionPack Subscription = new();");
                }

                w.Line("public readonly RenderOptionPack Render = new();");
                w.Line();

                // CLI params (path params other than subscription/rg, plus query params)
                foreach (var param in op.CliParams)
                {
                    if (
                        usesStorageAccount
                        && param.ParamIn == "path"
                        && param.UrlParameterName.Equals(
                            "accountName",
                            StringComparison.OrdinalIgnoreCase
                        )
                    )
                        continue; // absorbed by StorageAccountOptionPack

                    if (
                        usesResourcePack
                        && param.ParamIn == "path"
                        && param.UrlParameterName.Equals(
                            resourcePackConfig!.AbsorbedParam,
                            StringComparison.OrdinalIgnoreCase
                        )
                    )
                        continue; // absorbed by ResourceOptionPack

                    if ((usesResourceGroup || isMergedList) && param.CliFlag == "--resource-group")
                        continue; // absorbed by ResourceGroupOptionPack

                    // RenderOptionPack always adds --format/-f; rename colliding API params
                    var paramCliFlag = param.CliFlag == "--format" ? "--api-format" : param.CliFlag;
                    var paramPropName =
                        param.CliFlag == "--format" ? "ApiFormat" : param.PropertyName;

                    var requiredAttr = param.Required ? ", Required = true" : "";
                    if (!string.IsNullOrWhiteSpace(param.Description))
                        w.Line(
                            $"/// <summary>{EscapeXml(param.Description.Replace("\n", " ").Replace("\r", ""))}</summary>"
                        );
                    w.Line($"[CliOption(\"{paramCliFlag}\"{requiredAttr})]");
                    w.Line($"public partial string? {paramPropName} {{ get; }}");
                    w.Line();
                }

                // Body properties
                if (op.Body is { FlattenedProperties.Count: > 0 })
                {
                    foreach (var bp in op.Body.FlattenedProperties)
                    {
                        var typeName =
                            bp.TypeHint == "bool" ? "bool"
                            : bp.TypeHint == "int" ? "int"
                            : bp.TypeHint == "double" ? "double"
                            : "string";
                        var nullable = $"{typeName}?";
                        var requiredAttr = bp.Required ? ", Required = true" : "";

                        // RenderOptionPack always adds --format/-f; rename colliding API body params
                        var bpCliFlag = bp.CliFlag == "--format" ? "--api-format" : bp.CliFlag;
                        var bpPropName = bp.CliFlag == "--format" ? "ApiFormat" : bp.PropertyName;

                        if (!string.IsNullOrWhiteSpace(bp.Description))
                            w.Line(
                                $"/// <summary>{EscapeXml(bp.Description.Replace("\n", " ").Replace("\r", ""))}</summary>"
                            );
                        w.Line($"[CliOption(\"{bpCliFlag}\"{requiredAttr})]");
                        w.Line($"public partial {nullable} {bpPropName} {{ get; }}");
                        w.Line();
                    }
                }

                // --body-json escape hatch (always present if operation has a body)
                if (op.Body is not null)
                {
                    w.Line(
                        "/// <summary>Supply the full request body as a JSON string (overrides individual options).</summary>"
                    );
                    w.Line("[CliOption(\"--body-json\")]");
                    w.Line("public partial string? BodyJson { get; }");
                    w.Line();
                }

                // --no-wait for LRO
                if (op.IsLro)
                {
                    w.Line(
                        "/// <summary>Do not wait for the long-running operation to complete.</summary>"
                    );
                    w.Line("[CliOption(\"--no-wait\")]");
                    w.Line("public partial bool NoWait { get; }");
                    w.Line();
                }

                w.Line("private readonly AuthOptionPack _auth = auth;");
                w.Line();

                // ExecuteAsync
                w.Block(
                    "protected override async Task<int> ExecuteAsync(CancellationToken ct)",
                    () =>
                    {
                        w.Line("var log = DiagnosticOptionPack.GetLog();");
                        w.Line("var cred = _auth.GetCredential(log);");
                        if (isDataPlane)
                            w.Line(
                                $"var client = new AzureRestClient(cred, log, \"{dataplanePackConfig!.Scope}\");"
                            );
                        else
                            w.Line("var client = new AzureRestClient(cred, log);");

                        if (isDataPlane)
                            w.Line(
                                $"var dataplaneRef = (await {dataplanePackConfig!.FieldName}.ResolveDataplaneRefAsync(new ArmClient(cred), ct)).ToString().TrimEnd('/');"
                            );

                        if (usesResourcePack)
                            w.Line(
                                $"var {armIdVar} = (await {resourcePackConfig!.FieldName}.ResolveResourceAsync(new ArmClient(cred), ct)).Id.ToString();"
                            );

                        if (usesResourceNameResolver)
                        {
                            var primaryPropName =
                                primaryPathParam!.CliFlag == "--format"
                                    ? "ApiFormat"
                                    : primaryPathParam.PropertyName;
                            w.Line("var armClient = new ArmClient(cred);");
                            w.Line(
                                $"var (resolvedSub, resolvedRg, resolvedName) = await ResourceNameResolver.ResolveAsync("
                            );
                            w.Line(
                                $"    {primaryPropName}!, ResourceGroup, armClient, \"{resourceType}\", ct);"
                            );
                        }

                        // Resolve subscription ID (supports display-name shorthands like /s/prod)
                        if (
                            !isDataPlane
                            && !usesResourcePack
                            && !usesResourceNameResolver
                            && (
                                usesSubscription
                                || usesResourceGroup
                                || isMergedList
                                || usesStorageAccount
                            )
                        )
                        {
                            var subPack =
                                usesStorageAccount ? "StorageAccount.Subscription"
                                : usesResourceGroup || isMergedList ? "ResourceGroup.Subscription"
                                : "Subscription";
                            w.Line(
                                $"var subscriptionId = await {subPack}.RequireSubscriptionIdAsync(new ArmClient(cred));"
                            );
                        }

                        // Build path
                        if (isDataPlane)
                            EmitDataPlanePathBuilder(w, op, "dataplaneRef");
                        else if (usesResourcePack)
                            EmitResourcePackPathBuilder(w, op, resourcePackConfig!, armIdVar!);
                        else
                            EmitPathBuilder(
                                w,
                                op,
                                isMergedList,
                                usesResourceGroup,
                                usesSubscription,
                                usesStorageAccount,
                                usesResourceNameResolver,
                                primaryPathParam
                            );
                        w.Line();

                        if (op.IsPaged)
                        {
                            EmitPagedExecution(w, op);
                        }
                        else if (op.IsLro)
                        {
                            EmitLroExecution(w, op);
                        }
                        else if (op.Body is not null)
                        {
                            EmitBodyExecution(w, op);
                        }
                        else
                        {
                            EmitSimpleExecution(w, op);
                        }

                        w.Line("return 0;");
                    }
                );
            }
        );

        return w.ToString();
    }

    private static void EmitResourcePackPathBuilder(
        CodeWriter w,
        OperationModel op,
        ResourceOptionPackConfig resourcePackConfig,
        string armIdVar
    )
    {
        // Find the position of {absorbedParam} in the URL template (case-insensitive)
        var template = op.UrlTemplate;
        var token = $"{{{resourcePackConfig.AbsorbedParam}}}";
        var idx = template.IndexOf(token, StringComparison.OrdinalIgnoreCase);

        // Everything after the token is the suffix (e.g. "/keys/{keyName}")
        var suffix = idx >= 0 ? template[(idx + token.Length)..] : string.Empty;

        // Replace remaining path params in the suffix with property access
        foreach (var param in op.CliParams.Where(p => p.ParamIn == "path"))
        {
            suffix = suffix.Replace(
                $"{{{param.UrlParameterName}}}",
                $"{{{param.PropertyName}}}",
                StringComparison.OrdinalIgnoreCase
            );
        }

        if (string.IsNullOrEmpty(suffix))
            w.Line($"var path = {armIdVar};");
        else
            w.Line($"var path = $\"{{{armIdVar}}}{suffix}\";");
    }

    private static void EmitDataPlanePathBuilder(CodeWriter w, OperationModel op, string baseUrlVar)
    {
        var expr = op.UrlTemplate;

        // Replace path params with property access
        foreach (var param in op.CliParams.Where(p => p.ParamIn == "path"))
        {
            expr = expr.Replace(
                $"{{{param.UrlParameterName}}}",
                $"{{{param.PropertyName}}}",
                StringComparison.OrdinalIgnoreCase
            );
        }

        // Emit: var path = $"{baseUrlVar}/keys/{KeyName}/...";
        w.Line($"var path = $\"{{{baseUrlVar}}}{expr}\";");
    }

    private static void EmitPathBuilder(
        CodeWriter w,
        OperationModel op,
        bool isMergedList,
        bool usesResourceGroup,
        bool usesSubscription,
        bool usesStorageAccount = false,
        bool usesResourceNameResolver = false,
        CliParamModel? primaryPathParam = null
    )
    {
        if (isMergedList)
        {
            // Conditional path: RG-scope when --resource-group (or env var) is given,
            // subscription-scope otherwise. Both branches use ResourceGroupOptionPack.
            var rgPath = BuildPathExpression(
                op.UrlTemplate,
                op,
                usesResourceGroup: true,
                usesSubscription: true
            );
            var subPath = BuildMergedSubscriptionPath(op.MergedSubscriptionUrlTemplate!, op);
            w.Line(
                "var effectiveRg = ResourceGroup.ResourceGroupName ?? Environment.GetEnvironmentVariable(\"AZURE_RESOURCE_GROUP\");"
            );
            w.Line($"var path = effectiveRg is not null");
            w.Line($"    ? {rgPath}");
            w.Line($"    : {subPath};");
        }
        else if (usesResourceNameResolver)
        {
            var pathExpr = BuildPathExpressionWithResolver(op.UrlTemplate, op, primaryPathParam!);
            w.Line($"var path = {pathExpr};");
        }
        else
        {
            var pathExpr = BuildPathExpression(
                op.UrlTemplate,
                op,
                usesResourceGroup,
                usesSubscription,
                usesStorageAccount
            );
            w.Line($"var path = {pathExpr};");
        }
    }

    private static string BuildPathExpression(
        string urlTemplate,
        OperationModel op,
        bool usesResourceGroup,
        bool usesSubscription,
        bool usesStorageAccount = false
    )
    {
        var expr = urlTemplate;

        if (usesStorageAccount)
        {
            expr = expr.Replace(
                    "{subscriptionId}",
                    "{subscriptionId}",
                    StringComparison.OrdinalIgnoreCase
                )
                .Replace(
                    "{resourceGroupName}",
                    "{StorageAccount.ResourceGroup.RequireResourceGroupName()}",
                    StringComparison.OrdinalIgnoreCase
                )
                .Replace(
                    "{accountName}",
                    "{StorageAccount.RequireAccountName()}",
                    StringComparison.OrdinalIgnoreCase
                );
        }
        else
        {
            // subscriptionId is pre-resolved to a GUID variable above; just normalize casing
            expr = expr.Replace("{subscriptionId}", "{subscriptionId}")
                .Replace(
                    "{resourceGroupName}",
                    "{ResourceGroup.RequireResourceGroupName()}",
                    StringComparison.OrdinalIgnoreCase
                );
            if (usesResourceGroup)
                expr = expr.Replace(
                    "{resourceGroup}",
                    "{ResourceGroup.RequireResourceGroupName()}",
                    StringComparison.OrdinalIgnoreCase
                );
        }

        // Replace remaining path parameters with property access
        foreach (var param in op.CliParams.Where(p => p.ParamIn == "path"))
        {
            expr = expr.Replace(
                $"{{{param.UrlParameterName}}}",
                $"{{{param.PropertyName}}}",
                StringComparison.OrdinalIgnoreCase
            );
        }

        return $"$\"{expr}\"";
    }

    /// <summary>
    /// Builds the subscription-scope path for a merged list command.
    /// Always uses ResourceGroup.Subscription for subscriptionId.
    /// </summary>
    private static string BuildMergedSubscriptionPath(string urlTemplate, OperationModel op)
    {
        var expr = urlTemplate.Replace(
            "{subscriptionId}",
            "{subscriptionId}",
            StringComparison.OrdinalIgnoreCase
        );

        foreach (var param in op.CliParams.Where(p => p.ParamIn == "path"))
        {
            expr = expr.Replace(
                $"{{{param.UrlParameterName}}}",
                $"{{{param.PropertyName}}}",
                StringComparison.OrdinalIgnoreCase
            );
        }

        return $"$\"{expr}\"";
    }

    /// <summary>
    /// Builds a path expression for commands using ResourceNameResolver.
    /// Replaces subscriptionId and resourceGroupName with resolver variables, and the
    /// primary param with resolvedName. Remaining path params use property access.
    /// </summary>
    private static string BuildPathExpressionWithResolver(
        string urlTemplate,
        OperationModel op,
        CliParamModel primaryPathParam
    )
    {
        var expr = urlTemplate
            .Replace("{subscriptionId}", "{resolvedSub}", StringComparison.OrdinalIgnoreCase)
            .Replace("{resourceGroupName}", "{resolvedRg}", StringComparison.OrdinalIgnoreCase)
            .Replace(
                $"{{{primaryPathParam.UrlParameterName}}}",
                "{resolvedName}",
                StringComparison.OrdinalIgnoreCase
            );

        // Replace remaining path params with property access
        foreach (var param in op.CliParams.Where(p => p.ParamIn == "path" && p != primaryPathParam))
        {
            expr = expr.Replace(
                $"{{{param.UrlParameterName}}}",
                $"{{{param.PropertyName}}}",
                StringComparison.OrdinalIgnoreCase
            );
        }

        return $"$\"{expr}\"";
    }

    /// <summary>
    /// Extracts the ARM resource type from a URL template.
    /// E.g. ".../providers/Microsoft.ContainerService/managedClusters/..." → "Microsoft.ContainerService/managedClusters"
    /// </summary>
    private static string? ExtractResourceType(string urlTemplate)
    {
        var idx = urlTemplate.IndexOf("/providers/", StringComparison.OrdinalIgnoreCase);
        if (idx < 0)
            return null;
        var after = urlTemplate[(idx + "/providers/".Length)..];
        var segs = after.Split('/');
        return segs.Length >= 2 ? $"{segs[0]}/{segs[1]}" : null;
    }

    private static void EmitPagedExecution(CodeWriter w, OperationModel op)
    {
        var itemsProp = op.ItemsPropertyName ?? "value";
        var nextLinkProp = op.NextLinkPropertyName ?? "nextLink";

        w.Line(
            $"var allItems = client.GetAllAsync(path, \"{op.ApiVersion}\", \"{itemsProp}\", \"{nextLinkProp}\", ct);"
        );
        w.Line(
            "var renderer = Render.GetRendererFactory().CreateCollectionRenderer<System.Text.Json.Nodes.JsonNode>();"
        );
        w.Line("await renderer.RenderAllAsync(System.Console.Out, allItems, ct);");
    }

    private static void EmitLroExecution(CodeWriter w, OperationModel op)
    {
        if (op.Body is not null)
        {
            EmitBodyBuild(w, op);
            w.Line(
                $"var httpResp = await client.SendRawAsync(HttpMethod.{TitleCase(op.HttpMethod)}, path, \"{op.ApiVersion}\", body, ct);"
            );
        }
        else
        {
            w.Line(
                $"var httpResp = await client.SendRawAsync(HttpMethod.{TitleCase(op.HttpMethod)}, path, \"{op.ApiVersion}\", null, ct);"
            );
        }

        w.Block(
            "if (!NoWait)",
            () =>
            {
                w.Line(
                    $"var result = await LroPoller.PollAsync(httpResp, client, \"{op.ApiVersion}\", log, ct);"
                );
                w.Line(
                    "await Render.GetRendererFactory().CreateRendererForType(typeof(System.Text.Json.Nodes.JsonNode))"
                );
                w.Line("    .RenderAsync(System.Console.Out, result, ct);");
            }
        );
    }

    private static void EmitBodyExecution(CodeWriter w, OperationModel op)
    {
        EmitBodyBuild(w, op);
        w.Line(
            $"var result = await client.SendAsync(HttpMethod.{TitleCase(op.HttpMethod)}, path, \"{op.ApiVersion}\", body, ct);"
        );
        w.Line(
            "await Render.GetRendererFactory().CreateRendererForType(typeof(System.Text.Json.Nodes.JsonNode))"
        );
        w.Line("    .RenderAsync(System.Console.Out, result, ct);");
    }

    private static void EmitSimpleExecution(CodeWriter w, OperationModel op)
    {
        w.Line(
            $"var result = await client.SendAsync(HttpMethod.{TitleCase(op.HttpMethod)}, path, \"{op.ApiVersion}\", null, ct);"
        );
        w.Line(
            "await Render.GetRendererFactory().CreateRendererForType(typeof(System.Text.Json.Nodes.JsonNode))"
        );
        w.Line("    .RenderAsync(System.Console.Out, result, ct);");
    }

    private static void EmitBodyBuild(CodeWriter w, OperationModel op)
    {
        w.Line("var body = BodyJson is { } rawJson");
        w.Line("    ? JsonNode.Parse(rawJson)!.AsObject()");
        w.Line("    : new JsonObject");
        w.Line("    {");
        w.Indent();
        w.Indent();

        if (op.Body is { FlattenedProperties.Count: > 0 })
        {
            // Group nested properties by their parent JSON key
            var topLevelEntries = new Dictionary<string, List<BodyPropertyModel>>(
                StringComparer.OrdinalIgnoreCase
            );

            foreach (var bp in op.Body.FlattenedProperties)
            {
                if (bp.ParentJsonKey is not null)
                {
                    // Nested sub-property (e.g., sku.name)
                    if (!topLevelEntries.TryGetValue(bp.ParentJsonKey, out var subList))
                    {
                        subList = [];
                        topLevelEntries[bp.ParentJsonKey] = subList;
                    }

                    subList.Add(bp);
                }
                else
                {
                    // Top-level scalar
                    topLevelEntries[bp.JsonPropertyName] = [bp];
                }
            }

            foreach (var (key, props) in topLevelEntries)
            {
                if (props.Count == 1 && props[0].ParentJsonKey is null)
                {
                    // Simple scalar top-level property
                    var bp = props[0];
                    var bpProp = bp.CliFlag == "--format" ? "ApiFormat" : bp.PropertyName;
                    w.Line($"[\"{bp.JsonPropertyName}\"] = JsonValue.Create({bpProp}),");
                }
                else
                {
                    // Nested object (e.g., sku: { name: SkuName })
                    w.Line($"[\"{key}\"] = new JsonObject");
                    w.Line("{");
                    w.Indent();
                    foreach (var bp in props)
                    {
                        var bpProp = bp.CliFlag == "--format" ? "ApiFormat" : bp.PropertyName;
                        w.Line($"[\"{bp.JsonPropertyName}\"] = JsonValue.Create({bpProp}),");
                    }
                    w.Outdent();
                    w.Line("},");
                }
            }
        }

        w.Outdent();
        w.Line("};");
        w.Outdent();
    }

    private static string TitleCase(string method) =>
        method switch
        {
            "GET" => "Get",
            "PUT" => "Put",
            "POST" => "Post",
            "DELETE" => "Delete",
            "PATCH" => "Patch",
            _ => method,
        };

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
