using SpecGenerator.Modeling;

namespace SpecGenerator.Emitting;

/// <summary>
/// Emits a resource group command C# class that aggregates all leaf operation commands
/// for a single resource type (e.g. StorageAccountCommandDef).
/// </summary>
public static class ResourceCommandEmitter
{
    public static string Emit(ResourceGroupModel resource, string ns)
    {
        var w = new CodeWriter();

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591");
        w.Line("using Console.Cli.Shared;");
        w.Line();
        w.Line($"namespace {ns};");
        w.Line();

        w.Block($"public partial class {resource.ClassName}(AuthOptionPack auth) : CommandDef", () =>
        {
            w.Line($"public override string Name => \"{resource.CliName}\";");

            foreach (var op in resource.Operations)
            {
                var fieldName = NamingEngine.KebabToCSharpProperty(op.CliName);
                w.Line($"public readonly {op.ClassName} {fieldName} = new(auth);");
            }

            foreach (var sub in resource.Subgroups ?? [])
            {
                var fieldName = NamingEngine.KebabToCSharpProperty(sub.CliName);
                w.Line($"public readonly {sub.ClassName} {fieldName} = new(auth);");
            }
        });

        return w.ToString();
    }
}
