using SpecGenerator.Modeling;

namespace SpecGenerator.Emitting;

/// <summary>
/// Emits the partial RootCommandDef patch that wires generated service commands
/// into the root command via the InitGeneratedCommands partial method.
/// </summary>
public static class RootPatchEmitter
{
    public static string Emit(List<ServiceModel> services, string generatedNs)
    {
        var w = new CodeWriter();

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591");
        w.Line($"using {generatedNs};");
        w.Line();
        w.Line("namespace Console.Cli;");
        w.Line();

        w.Block(
            "public partial class RootCommandDef",
            () =>
            {
                foreach (var service in services)
                {
                    var fieldName = NamingEngine.KebabToCSharpProperty(service.CliName);
                    // Not readonly: C# does not allow assigning readonly fields in partial methods
                    w.Line($"public {service.ClassName} {fieldName} = null!;");
                }

                w.Line();

                // Static set of known service CLI names — used by Program.cs to validate
                // the pre-scanned target service before constructing the command tree.
                w.Line("internal static readonly System.Collections.Generic.HashSet<string> KnownServices =");
                w.Line("    new(System.StringComparer.Ordinal)");
                w.Line("    {");
                foreach (var service in services)
                    w.Line($"        {Quote(service.CliName)},");
                w.Line("    };");

                w.Line();

                w.Block(
                    "partial void InitGeneratedCommands(string? targetService)",
                    () =>
                    {
                        foreach (var service in services)
                        {
                            var fieldName = NamingEngine.KebabToCSharpProperty(service.CliName);
                            w.Line(
                                $"if (targetService is null || targetService == {Quote(service.CliName)})"
                            );
                            w.Line($"    {fieldName} = new {service.ClassName}(Auth);");
                        }
                    }
                );
            }
        );

        return w.ToString();
    }

    private static string Quote(string s) =>
        $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
}
