using SpecGenerator.Modeling;

namespace SpecGenerator.Emitting;

/// <summary>
/// Emits the top-level service command C# class (e.g. StorageCommandDef).
/// </summary>
public static class ServiceCommandEmitter
{
    public static string Emit(ServiceModel service, string ns)
    {
        var w = new CodeWriter();

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591");
        w.Line("using Console.Cli.Shared;");
        w.Line();
        w.Line($"namespace {ns};");
        w.Line();

        if (service.Description is { Length: > 0 })
            w.Line($"/// <summary>{EscapeXml(service.Description)}</summary>");
        if (service.DetailedDescription is { Length: > 0 })
            w.Line($"/// <remarks>{EscapeXml(service.DetailedDescription)}</remarks>");
        w.Block($"public partial class {service.ClassName}(AuthOptionPack auth) : CommandDef", () =>
        {
            w.Line($"public override string Name => \"{service.CliName}\";");
            if (service.IsDataPlane)
                w.Line("protected override bool IsDataPlane => true;");

            foreach (var resource in service.Resources)
            {
                var fieldName = NamingEngine.KebabToCSharpProperty(resource.CliName);
                w.Line($"public readonly {resource.ClassName} {fieldName} = new(auth);");
            }
        });

        return w.ToString();
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
