using SpecGenerator.Modeling;

namespace SpecGenerator.Emitting;

/// <summary>
/// Emits the top-level service command C# class (e.g. StorageCommandDef).
/// </summary>
public static class ServiceCommandEmitter
{
    public static string Emit(ServiceModel service, string ns)
    {
        var w = new CodeWriter();

        w.Line("// <auto-generated/>");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591");
        w.Line("using Console.Cli.Shared;");
        w.Line();
        w.Line($"namespace {ns};");
        w.Line();

        w.Block($"public partial class {service.ClassName}(AuthOptionPack auth) : CommandDef", () =>
        {
            w.Line($"public override string Name => \"{service.CliName}\";");

            foreach (var resource in service.Resources)
            {
                var fieldName = NamingEngine.KebabToCSharpProperty(resource.CliName);
                w.Line($"public readonly {resource.ClassName} {fieldName} = new(auth);");
            }
        });

        return w.ToString();
    }
}
