using static CliGenerator.Tests.CliGeneratorTestHelpers;

namespace CliGenerator.Tests;

[TestClass]
public class CliOptionGeneratorStructureTests
{
    [TestMethod]
    public void ChildCommandAndOptionPack_EmitGeneratedChildrenWiring()
    {
        var text = GenerateForBody(
            "RootCommand.g.cs",
            """
            public partial class AuthPack : OptionPack { }
            public partial class SubCommand : CommandDef { }

            public partial class RootCommand : CommandDef
            {
                public AuthPack Auth = new();
                public SubCommand Sub = new();

                [CliOption("--name")]
                public partial string? Name { get; }
            }
            """
        );
        AssertContainsAll(
            text,
            "protected override bool HasGeneratedChildren => true;",
            "((global::Console.Cli.OptionPack)Auth).AddOptionsTo(cmd);",
            "cmd.Add(((global::Console.Cli.CommandDef)Sub).Build());"
        );
    }

    [TestMethod]
    public void ClassSummaryAndRemarks_EmitOverrides()
    {
        var text = GenerateForBody(
            "DocsCommand.g.cs",
            """
            /// <summary>List subscriptions</summary>
            /// <remarks>
            ///   First line.
            ///   Second line.
            /// </remarks>
            public partial class DocsCommand : CommandDef
            {
                [CliOption("--name")]
                public partial string? Name { get; }
            }
            """
        );
        AssertContainsAll(
            text,
            "public override string Description => \"List subscriptions\";",
            "public override string? DetailedDescription => \"First line.",
            "Second line.\";"
        );
    }

    [TestMethod]
    public void ExplicitDescriptionOverride_TakesPrecedenceOverXmlSummary()
    {
        var text = GenerateForBody(
            "ExplicitDescriptionCommand.g.cs",
            """
            /// <summary>XML summary description</summary>
            /// <remarks>XML remarks body.</remarks>
            public partial class ExplicitDescriptionCommand : CommandDef
            {
                public override string Description => "Property description";

                [CliOption("--name")]
                public partial string? Name { get; }
            }
            """
        );

        Assert.IsFalse(
            text.Contains("public override string Description => \"XML summary description\";")
        );
        Assert.IsTrue(
            text.Contains("public override string? DetailedDescription => \"XML remarks body.\";")
        );
    }

    [TestMethod]
    public void ExplicitDetailedDescriptionOverride_TakesPrecedenceOverXmlRemarks()
    {
        var text = GenerateForBody(
            "ExplicitDetailedDescriptionCommand.g.cs",
            """
            /// <summary>XML summary description</summary>
            /// <remarks>XML remarks body.</remarks>
            public partial class ExplicitDetailedDescriptionCommand : CommandDef
            {
                public override string? DetailedDescription => "Property detailed description";

                [CliOption("--name")]
                public partial string? Name { get; }
            }
            """
        );

        Assert.IsFalse(
            text.Contains("public override string? DetailedDescription => \"XML remarks body.\";")
        );
    }

    [TestMethod]
    public void OptionPackChild_EmitsAddChildPacksToWiring()
    {
        var text = GenerateForBody(
            "ParentPack.g.cs",
            """
            public partial class ChildPack : OptionPack
            {
                [CliOption("--child")]
                public partial string? Child { get; }
            }

            public partial class ParentPack : OptionPack
            {
                public ChildPack Child = new();

                [CliOption("--parent")]
                public partial string? Parent { get; }
            }
            """
        );
        AssertContainsAll(
            text,
            "protected override void AddChildPacksTo(global::System.CommandLine.Command cmd)",
            "((global::Console.Cli.OptionPack)Child).AddOptionsTo(cmd);"
        );
    }

    [TestMethod]
    public void GeneratedFile_HasExpectedHeaderPragmasAndUsings()
    {
        var text = GenerateForBody(
            "HeaderCommand.g.cs",
            """
            public partial class HeaderCommand : CommandDef
            {
                [CliOption("--name")]
                public partial string? Name { get; }
            }
            """
        );
        AssertContainsInOrder(
            text,
            "// <auto-generated/>",
            "#nullable enable",
            "#pragma warning disable CS1591",
            "using System.CommandLine;",
            "using System.Linq;",
            "namespace TestApp;",
            "partial class HeaderCommand"
        );
    }

    [TestMethod]
    public void GlobalNamespace_Class_DoesNotEmitNamespaceLine()
    {
        var source = ComposeSource(
            """
            public partial class GlobalCommand : Console.Cli.CommandDef
            {
                [Console.Cli.CliOption("--name")]
                public partial string? Name { get; }
            }
            """
        );

        var text = GetGeneratedText(RunAndGetResult(source), "GlobalCommand.g.cs");
        Assert.IsFalse(
            text.Contains("namespace "),
            "Global namespace classes should not emit namespace declaration"
        );
        Assert.IsTrue(text.Contains("partial class GlobalCommand"));
    }

    [TestMethod]
    public void DeepNamespace_Class_EmitsCorrectNamespaceLine()
    {
        var text = GenerateFor(
            ComposeSource(
                """
                namespace Company.Product.Feature.Commands
                {
                    using Console.Cli;

                    public partial class DeepCommand : CommandDef
                    {
                        [CliOption("--name")]
                        public partial string? Name { get; }
                    }
                }
                """
            ),
            "DeepCommand.g.cs"
        );
        AssertContainsAll(
            text,
            "namespace Company.Product.Feature.Commands;",
            "partial class DeepCommand"
        );
    }

    [TestMethod]
    public void MultiOption_DeclarationOrder_IsPreserved()
    {
        var text = GenerateForBody(
            "OrderedCommand.g.cs",
            """
            public partial class OrderedCommand : CommandDef
            {
                [CliOption("--first")]
                public partial string? First { get; }

                [CliOption("--second")]
                public partial bool Second { get; }

                [CliOption("--third")]
                public partial int Third { get; }
            }
            """
        );

        AssertContainsInOrder(
            text,
            "_opt_First = new(\"--first\"",
            "_opt_Second = new(\"--second\"",
            "_opt_Third = new(\"--third\""
        );

        AssertContainsInOrder(
            text,
            "public partial string? First =>",
            "public partial bool Second =>",
            "public partial int Third =>"
        );

        AssertContainsInOrder(
            text,
            "cmd.Add(_opt_First);",
            "cmd.Add(_opt_Second);",
            "cmd.Add(_opt_Third);"
        );
    }

    [TestMethod]
    public void CommandDef_WithOnlyOptionPackChildren_EmitsChildrenOverrides()
    {
        var text = GenerateForBody(
            "ParentCommand.g.cs",
            """
            public partial class ChildPack : OptionPack { }

            public partial class ParentCommand : CommandDef
            {
                public ChildPack Child = new();

                [CliOption("--name")]
                public partial string? Name { get; }
            }
            """
        );
        AssertContainsAll(
            text,
            "protected override bool HasGeneratedChildren => true;",
            "protected override void AddGeneratedChildren(global::System.CommandLine.Command cmd)",
            "((global::Console.Cli.OptionPack)Child).AddOptionsTo(cmd);"
        );
    }

    [TestMethod]
    public void OptionPack_WithoutChildPacks_DoesNotEmitAddChildPacksOverride()
    {
        var text = GenerateForBody(
            "SoloPack.g.cs",
            """
            public partial class SoloPack : OptionPack
            {
                [CliOption("--name")]
                public partial string? Name { get; }
            }
            """
        );
        Assert.IsFalse(text.Contains("protected override void AddChildPacksTo"));
        Assert.IsTrue(text.Contains("protected override void AddGeneratedOptions"));
    }

    [TestMethod]
    public void Determinism_SameInput_ProducesSameGeneratedOutput()
    {
        var source = InTestApp(
            """
            public partial class StableCommand : CommandDef
            {
                [CliOption("--name")]
                public partial string? Name { get; }

                [CliOption("--count")]
                public partial int Count { get; }
            }
            """
        );

        var first = GetGeneratedText(RunAndGetResult(source), "StableCommand.g.cs");
        var second = GetGeneratedText(RunAndGetResult(source), "StableCommand.g.cs");

        Assert.AreEqual(
            first,
            second,
            "Generated output should be deterministic for identical input"
        );
    }

    [TestMethod]
    public void EmptySummary_DoesNotEmitDescriptionOverride()
    {
        var text = GenerateForBody(
            "EmptySummaryCommand.g.cs",
            """
            /// <summary>
            ///
            /// </summary>
            public partial class EmptySummaryCommand : CommandDef
            {
                [CliOption("--name")]
                public partial string? Name { get; }
            }
            """
        );
        Assert.IsFalse(text.Contains("public override string Description =>"));
    }
}
