namespace CliGenerator;

internal static class AttributeSources
{
    public const string Source = """
        // <auto-generated/>
        #nullable enable
        using System;

        namespace Console.Cli
        {
            /// <summary>Marks a property as a CLI option. The generator wires it up to System.CommandLine.</summary>
            [AttributeUsage(AttributeTargets.Property)]
            internal sealed class CliOptionAttribute : Attribute
            {
                public string[] Aliases { get; }
                public bool Required { get; set; }
                public bool Global { get; set; }
                public Type? ConverterType { get; set; }
                /// <summary>A C# expression for the default value, e.g. "true" or "new() { \"a\", \"b\" }".</summary>
                public string? DefaultExpr { get; set; }
                public CliOptionAttribute(params string[] aliases) { Aliases = aliases; }
            }

            /// <summary>Declares the default parser for a type.</summary>
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
            internal sealed class CliParserAttribute : Attribute
            {
                public Type ConverterType { get; }
                public CliParserAttribute(Type converterType) { ConverterType = converterType; }
            }

            /// <summary>Overrides arity for a [CliOption] property.</summary>
            [AttributeUsage(AttributeTargets.Property)]
            internal sealed class ArityAttribute : Attribute
            {
                public int Min { get; }
                public int Max { get; }
                public ArityAttribute(int min, int max) { Min = min; Max = max; }
            }
        }
        """;
}
